const recommendationData = [
  {
    id: 1,
    namaHotel: "Amanjiwo",
    rating: "4.7",
    kota: "Central Java",
    priceRange: "Rp 199.999 - Rp 594.285",
    description:
      "Surrounded by tropical forests, this upscale all-suite hotel in stone buildings is 4 km both from the 9th-century Borobudur Temple and from ornate Pawon temple.",
    latitude: -6.2,
    longitude: 106.816666,
    imageUrl: "https://www.aman.com/sites/default/files/styles/central_carousel_large/public/2021-03/Aman_Amanjiwo_Gallery_1.jpg?itok=yTRJz-1S",
  },
  {
    id: 2,
    namaHotel: "Four Seasons Resort Bali At Sayan",
    rating: "4.7",
    kota: "Bali",
    priceRange: "",
    description:
      "Nestled in jungle beside the Ayung River, this luxury resort is 2 km from the Blanco Renaissance Museum, 7 km from the upscale shops of Ubud and 9 km from the ancient carvings of the Goa Gajah cave.",
    latitude: -6.2,
    longitude: 106.816666,
    imageUrl: "https://i.ytimg.com/vi/QDTf_shOqF4/maxresdefault.jpg",
  },
  {
    id: 3,
    namaHotel: "Wapa di Ume Sidemen",
    rating: "4.7",
    kota: "Bali",
    priceRange: "",
    description:
      "This boutique bolthole in the 'New Ubud' reclines in a rich sweep of rice paddies on the lower slopes of Mount Agung. Private pools star alongside a glorious two-tier infinity pool, and there's a superb spa and tempting restaurant, too. ",
    latitude: -6.2,
    longitude: 106.816666,
    imageUrl: "https://pix10.agoda.net/hotelImages/4437100/-1/61e48b243faf99ab5f23b3d8a3d2f7aa.jpg?ca=0&ce=1&s=1024x768",
  },
  {
    id: 4,
    namaHotel: "Sheraton Belitung Resort",
    rating: "4.7",
    kota: "Bangka Belitung",
    priceRange: "",
    description:
      "Stay near the beach and discover one of Indonesia's most beautiful destinations at Sheraton Belitung Resort. Nestled between pristine white silica beaches and sparkling turquoise waters on the untouched island of Belitung, our sophisticated hotel serves up a vision of paradise. Revive your spirit at our on-site gym, tranquil spa and fabulous outdoor infinity pool.",
    latitude: -6.2,
    longitude: 106.816666,
    imageUrl: "https://asset.kompas.com/crops/5wHc1cXwBD9zdnxvXt63TJCrV84=/0x0:1731x1154/750x500/data/photo/2020/09/05/5f530b26a5f39.jpg",
  },
  {
    id: 5,
    namaHotel: "The Sanchaya",
    rating: "4.7",
    kota: "Bintan Islands",
    priceRange: "",
    description:
      "Among beachfront gardens, this grand, Colonial-style resort is 8 km from Bandar Bentan Telani Ferry Terminal and 10 km from the 18-hole Laguna Bintan Golf Club.",
    latitude: -6.2,
    longitude: 106.816666,
    imageUrl: "https://pix10.agoda.net/hotelImages/7541458/0/96482746efdd0d0f9aa54f28f56f76fb.jpg?ca=23&ce=0&s=1024x768",
  },
  {
    id: 6,
    namaHotel: "Whiz Prime Hotel Hasanuddin Makasar",
    rating: "4.7",
    kota: "North Sulawesi",
    priceRange: "",
    description:
      "Less than 1 km from Fort Rotterdam, this straightforward hotel with a quirky, contemporary exterior is a 4-minute walk from a bus stop and 2 km from Losari Beach.",
    latitude: -6.2,
    longitude: 106.816666,
    imageUrl: "https://cf.bstatic.com/xdata/images/hotel/max1280x900/64263030.jpg?k=39b10adcc7fd9fb4969fcbe66d3cdaeb2752f34aa7c8d62992fa79c7568f5dec&o=&hp=1",
  },
  {
    id: 7,
    namaHotel: "InterContinental Bandung Dago Pakar, an IHG Hotel",
    rating: "4.7",
    kota: "Bandung",
    priceRange: "",
    description:
      "A 12-minute walk from Mountain View Golf Club, this upscale hotel on the outskirts of Bandung is 4 km from Djuanda Forest Park and 10 km from Bandung train station.",
    latitude: -6.2,
    longitude: 106.816666,
    imageUrl: "https://digital.ihg.com/is/image/ihg/intercontinental-bandung-7089548027-2x1?fit=fit,1&wid=2400&hei=1200&qlt=85,0&resMode=sharp2&op_usm=1.75,0.9,2,0",
  },
  {
    id: 8,
    namaHotel: "The Edge",
    rating: "4.7",
    kota: "Bali",
    priceRange: "",
    description:
      "On a clifftop with panoramic views of the Indian Ocean, this upscale resort is 7 km from Pura Luhur Uluwatu temple and 8 km from Garuda Wisnu Kencana Cultural Park.",
    latitude: -6.2,
    longitude: 106.816666,
    imageUrl: "https://media.cntraveler.com/photos/5db088f5ceb13600094a42af/3:2/w_2445,h_1630,c_limit/the-Edge-Day---Courtesy-of-Related-Oxford-.jpg",
  },
  {
    id: 9,
    namaHotel: "Bulgari Resort Bali",
    rating: "4.7",
    kota: "Bali",
    priceRange: "",
    description:
      "Overlooking the Indian Ocean, this posh cliff-top resort is 6 km from the Pura Luhur Uluwatu temple and 9 km from the Garuda Wisnu Kencana Cultural Park.",
    latitude: -6.2,
    longitude: 106.816666,
    imageUrl: "https://cf.bstatic.com/xdata/images/hotel/max500/213278033.jpg?k=c17a27c010aa5eabaa8c6002e2f8cef929486e71d61de9872570757478526f0e&o=&hp=1",
  },
  {
    id: 10,
    namaHotel: "Indra Maya Villas",
    rating: "4.7",
    kota: "Riau Islands",
    priceRange: "",
    description:
      "Set in the 33-hectare Nirwana Gardens coastal resort, these airy, low-key villas are 4.7 km from Laguna Bintan Golf Club and 10 km from Bandar Bentan Telani Ferry Terminal.",
    latitude: -6.2,
    longitude: 106.816666,
    imageUrl: "https://www.bintan-resorts.com/wp-content/uploads/2015/02/nirwana-gardens-indra-maya-pool-villa.jpg",
  },
  {
    id: 11,
    namaHotel: "The Langham",
    rating: "4.7",
    kota: "Jakarta",
    priceRange: "",
    description:
      "This swanky hotel in a sleek high-rise is a 14-minute walk from both Gelora Bung Karno Sports Complex and Senayan MRT station. It's 7 km from the National Museum of Indonesia.",
    latitude: -6.2,
    longitude: 106.816666,
    imageUrl: "https://assets.langhamhotels.com/is/image/langhamhotelsstage/tljkt-one-bedroom-suite-living-room:Medium?wid=1800&hei=1011",
  },
  {
    id: 12,
    namaHotel: "Taman Simalem Resort",
    rating: "4.7",
    kota: "North Sumatra",
    priceRange: "",
    description:
      "Set on a cliff overlooking Lake Toba, this laid-back resort is 14 km from Sipisopiso, a dramatic waterfall, and 13 km from Sapo Juma Taman Bunga, a flower garden. It’s 135 km from Kualanamu International Airport.",
    latitude: -6.2,
    longitude: 106.816666,
    imageUrl: "https://cf.bstatic.com/xdata/images/hotel/max1024x768/193809473.jpg?k=ae4e71c30b90c3e15e119c0b9e9874952f99860e786760fac3dfc4651f89af7d&o=&hp=1",
  },
  {
    id: 13,
    namaHotel: "Loccal Collection Hotel",
    rating: "4.7",
    kota: "East Nusa Tenggara",
    priceRange: "",
    description:
      "In whitewashed buildings set on a hillside, this chic hotel overlooking the Flores Sea is 2 km from the Bukit Cinta viewing point and 3 km from Komodo International Airport.",
    latitude: -6.2,
    longitude: 106.816666,
    imageUrl: "http://nasional.baranewsaceh.co/wp-content/uploads/2021/08/307924536.jpg",
  },
  {
    id: 14,
    namaHotel: "Hotel Tentrem Yogyakarta",
    rating: "4.7",
    kota: "Yogyakarta",
    priceRange: "",
    description:
      "Among shops and restaurants, this lavish hotel is 2.9 km from the markets on buzzy Jalan Malioboro, and 5 km from Keraton Ngayogyakarta Hadiningrat palace.",
    latitude: -6.2,
    longitude: 106.816666,
    imageUrl: "https://d2ile4x3f22snf.cloudfront.net/wp-content/uploads/sites/210/2017/11/26090747/2200-1200-Pool-21.jpg",
  },
  {
    id: 15,
    longitude: 106.816666,
    namaHotel: "Padma Hotel Bandung",
    rating: "4.7",
    kota: "Bandung",
    priceRange: "",
    description:
      "Surrounded by lush greenery, this modern hotel is 4.1 km from Bandung Zoo, 6.7 km from the Museum Geologi featuring fossils and 8 km from upscale shopping at Braga Street.",
    latitude: -6.2,
    longitude: 106.816666,
    imageUrl: "https://www.indoplaces.com/foto/hotel/padma-hotel-bandung.jpg",
  },
];
