const surveyData = [
  "Shuttle Service",
  "Sports and Recreations",
  "Kids and Pets",
  "Transportation",
  "Connectivity",
  "Accessibilty",
  "Things to Do",
  "General",
  "Public Facilities",
  "Nearby Facilities",
  "Business Facilities",
  "In-room Facilities",
  "Hotel Services",
  "Food and Drinks",
  "Fast Food",
  "Shop & Gifts",
  "Business",
  "Transportation Hub",
  "Casual Dining",
  "Nightlife",
  "Park & Zoo",
  "Public Service",
  "Arts & Sciences",
  "Fine Dining",
  "Sport",
  "Quick Bites",
  "Education",
  "Street Food",
  "Activity & Games",
  "Cafe",
  "Entertainment",
  "Food Court",
  "Sight & Landmark",
];

module.exports = surveyData;
